package com.rabbit.smart.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysRoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    public SysRoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRidIsNull() {
            addCriterion("RID is null");
            return (Criteria) this;
        }

        public Criteria andRidIsNotNull() {
            addCriterion("RID is not null");
            return (Criteria) this;
        }

        public Criteria andRidEqualTo(String value) {
            addCriterion("RID =", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotEqualTo(String value) {
            addCriterion("RID <>", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThan(String value) {
            addCriterion("RID >", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThanOrEqualTo(String value) {
            addCriterion("RID >=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThan(String value) {
            addCriterion("RID <", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThanOrEqualTo(String value) {
            addCriterion("RID <=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLike(String value) {
            addCriterion("RID like", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotLike(String value) {
            addCriterion("RID not like", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidIn(List<String> values) {
            addCriterion("RID in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotIn(List<String> values) {
            addCriterion("RID not in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidBetween(String value1, String value2) {
            addCriterion("RID between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotBetween(String value1, String value2) {
            addCriterion("RID not between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andRnameIsNull() {
            addCriterion("RNAME is null");
            return (Criteria) this;
        }

        public Criteria andRnameIsNotNull() {
            addCriterion("RNAME is not null");
            return (Criteria) this;
        }

        public Criteria andRnameEqualTo(String value) {
            addCriterion("RNAME =", value, "rname");
            return (Criteria) this;
        }

        public Criteria andRnameNotEqualTo(String value) {
            addCriterion("RNAME <>", value, "rname");
            return (Criteria) this;
        }

        public Criteria andRnameGreaterThan(String value) {
            addCriterion("RNAME >", value, "rname");
            return (Criteria) this;
        }

        public Criteria andRnameGreaterThanOrEqualTo(String value) {
            addCriterion("RNAME >=", value, "rname");
            return (Criteria) this;
        }

        public Criteria andRnameLessThan(String value) {
            addCriterion("RNAME <", value, "rname");
            return (Criteria) this;
        }

        public Criteria andRnameLessThanOrEqualTo(String value) {
            addCriterion("RNAME <=", value, "rname");
            return (Criteria) this;
        }

        public Criteria andRnameLike(String value) {
            addCriterion("RNAME like", value, "rname");
            return (Criteria) this;
        }

        public Criteria andRnameNotLike(String value) {
            addCriterion("RNAME not like", value, "rname");
            return (Criteria) this;
        }

        public Criteria andRnameIn(List<String> values) {
            addCriterion("RNAME in", values, "rname");
            return (Criteria) this;
        }

        public Criteria andRnameNotIn(List<String> values) {
            addCriterion("RNAME not in", values, "rname");
            return (Criteria) this;
        }

        public Criteria andRnameBetween(String value1, String value2) {
            addCriterion("RNAME between", value1, value2, "rname");
            return (Criteria) this;
        }

        public Criteria andRnameNotBetween(String value1, String value2) {
            addCriterion("RNAME not between", value1, value2, "rname");
            return (Criteria) this;
        }

        public Criteria andCjrIsNull() {
            addCriterion("CJR is null");
            return (Criteria) this;
        }

        public Criteria andCjrIsNotNull() {
            addCriterion("CJR is not null");
            return (Criteria) this;
        }

        public Criteria andCjrEqualTo(String value) {
            addCriterion("CJR =", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotEqualTo(String value) {
            addCriterion("CJR <>", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrGreaterThan(String value) {
            addCriterion("CJR >", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrGreaterThanOrEqualTo(String value) {
            addCriterion("CJR >=", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLessThan(String value) {
            addCriterion("CJR <", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLessThanOrEqualTo(String value) {
            addCriterion("CJR <=", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLike(String value) {
            addCriterion("CJR like", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotLike(String value) {
            addCriterion("CJR not like", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrIn(List<String> values) {
            addCriterion("CJR in", values, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotIn(List<String> values) {
            addCriterion("CJR not in", values, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrBetween(String value1, String value2) {
            addCriterion("CJR between", value1, value2, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotBetween(String value1, String value2) {
            addCriterion("CJR not between", value1, value2, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjsjIsNull() {
            addCriterion("CJSJ is null");
            return (Criteria) this;
        }

        public Criteria andCjsjIsNotNull() {
            addCriterion("CJSJ is not null");
            return (Criteria) this;
        }

        public Criteria andCjsjEqualTo(Date value) {
            addCriterion("CJSJ =", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotEqualTo(Date value) {
            addCriterion("CJSJ <>", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjGreaterThan(Date value) {
            addCriterion("CJSJ >", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjGreaterThanOrEqualTo(Date value) {
            addCriterion("CJSJ >=", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjLessThan(Date value) {
            addCriterion("CJSJ <", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjLessThanOrEqualTo(Date value) {
            addCriterion("CJSJ <=", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjIn(List<Date> values) {
            addCriterion("CJSJ in", values, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotIn(List<Date> values) {
            addCriterion("CJSJ not in", values, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjBetween(Date value1, Date value2) {
            addCriterion("CJSJ between", value1, value2, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotBetween(Date value1, Date value2) {
            addCriterion("CJSJ not between", value1, value2, "cjsj");
            return (Criteria) this;
        }

        public Criteria andIpksIsNull() {
            addCriterion("IPKS is null");
            return (Criteria) this;
        }

        public Criteria andIpksIsNotNull() {
            addCriterion("IPKS is not null");
            return (Criteria) this;
        }

        public Criteria andIpksEqualTo(String value) {
            addCriterion("IPKS =", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksNotEqualTo(String value) {
            addCriterion("IPKS <>", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksGreaterThan(String value) {
            addCriterion("IPKS >", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksGreaterThanOrEqualTo(String value) {
            addCriterion("IPKS >=", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksLessThan(String value) {
            addCriterion("IPKS <", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksLessThanOrEqualTo(String value) {
            addCriterion("IPKS <=", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksLike(String value) {
            addCriterion("IPKS like", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksNotLike(String value) {
            addCriterion("IPKS not like", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksIn(List<String> values) {
            addCriterion("IPKS in", values, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksNotIn(List<String> values) {
            addCriterion("IPKS not in", values, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksBetween(String value1, String value2) {
            addCriterion("IPKS between", value1, value2, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksNotBetween(String value1, String value2) {
            addCriterion("IPKS not between", value1, value2, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpjsIsNull() {
            addCriterion("IPJS is null");
            return (Criteria) this;
        }

        public Criteria andIpjsIsNotNull() {
            addCriterion("IPJS is not null");
            return (Criteria) this;
        }

        public Criteria andIpjsEqualTo(String value) {
            addCriterion("IPJS =", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsNotEqualTo(String value) {
            addCriterion("IPJS <>", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsGreaterThan(String value) {
            addCriterion("IPJS >", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsGreaterThanOrEqualTo(String value) {
            addCriterion("IPJS >=", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsLessThan(String value) {
            addCriterion("IPJS <", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsLessThanOrEqualTo(String value) {
            addCriterion("IPJS <=", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsLike(String value) {
            addCriterion("IPJS like", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsNotLike(String value) {
            addCriterion("IPJS not like", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsIn(List<String> values) {
            addCriterion("IPJS in", values, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsNotIn(List<String> values) {
            addCriterion("IPJS not in", values, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsBetween(String value1, String value2) {
            addCriterion("IPJS between", value1, value2, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsNotBetween(String value1, String value2) {
            addCriterion("IPJS not between", value1, value2, "ipjs");
            return (Criteria) this;
        }

        public Criteria andJsyxqIsNull() {
            addCriterion("JSYXQ is null");
            return (Criteria) this;
        }

        public Criteria andJsyxqIsNotNull() {
            addCriterion("JSYXQ is not null");
            return (Criteria) this;
        }

        public Criteria andJsyxqEqualTo(Date value) {
            addCriterion("JSYXQ =", value, "jsyxq");
            return (Criteria) this;
        }

        public Criteria andJsyxqNotEqualTo(Date value) {
            addCriterion("JSYXQ <>", value, "jsyxq");
            return (Criteria) this;
        }

        public Criteria andJsyxqGreaterThan(Date value) {
            addCriterion("JSYXQ >", value, "jsyxq");
            return (Criteria) this;
        }

        public Criteria andJsyxqGreaterThanOrEqualTo(Date value) {
            addCriterion("JSYXQ >=", value, "jsyxq");
            return (Criteria) this;
        }

        public Criteria andJsyxqLessThan(Date value) {
            addCriterion("JSYXQ <", value, "jsyxq");
            return (Criteria) this;
        }

        public Criteria andJsyxqLessThanOrEqualTo(Date value) {
            addCriterion("JSYXQ <=", value, "jsyxq");
            return (Criteria) this;
        }

        public Criteria andJsyxqIn(List<Date> values) {
            addCriterion("JSYXQ in", values, "jsyxq");
            return (Criteria) this;
        }

        public Criteria andJsyxqNotIn(List<Date> values) {
            addCriterion("JSYXQ not in", values, "jsyxq");
            return (Criteria) this;
        }

        public Criteria andJsyxqBetween(Date value1, Date value2) {
            addCriterion("JSYXQ between", value1, value2, "jsyxq");
            return (Criteria) this;
        }

        public Criteria andJsyxqNotBetween(Date value1, Date value2) {
            addCriterion("JSYXQ not between", value1, value2, "jsyxq");
            return (Criteria) this;
        }

        public Criteria andShqxIsNull() {
            addCriterion("SHQX is null");
            return (Criteria) this;
        }

        public Criteria andShqxIsNotNull() {
            addCriterion("SHQX is not null");
            return (Criteria) this;
        }

        public Criteria andShqxEqualTo(String value) {
            addCriterion("SHQX =", value, "shqx");
            return (Criteria) this;
        }

        public Criteria andShqxNotEqualTo(String value) {
            addCriterion("SHQX <>", value, "shqx");
            return (Criteria) this;
        }

        public Criteria andShqxGreaterThan(String value) {
            addCriterion("SHQX >", value, "shqx");
            return (Criteria) this;
        }

        public Criteria andShqxGreaterThanOrEqualTo(String value) {
            addCriterion("SHQX >=", value, "shqx");
            return (Criteria) this;
        }

        public Criteria andShqxLessThan(String value) {
            addCriterion("SHQX <", value, "shqx");
            return (Criteria) this;
        }

        public Criteria andShqxLessThanOrEqualTo(String value) {
            addCriterion("SHQX <=", value, "shqx");
            return (Criteria) this;
        }

        public Criteria andShqxLike(String value) {
            addCriterion("SHQX like", value, "shqx");
            return (Criteria) this;
        }

        public Criteria andShqxNotLike(String value) {
            addCriterion("SHQX not like", value, "shqx");
            return (Criteria) this;
        }

        public Criteria andShqxIn(List<String> values) {
            addCriterion("SHQX in", values, "shqx");
            return (Criteria) this;
        }

        public Criteria andShqxNotIn(List<String> values) {
            addCriterion("SHQX not in", values, "shqx");
            return (Criteria) this;
        }

        public Criteria andShqxBetween(String value1, String value2) {
            addCriterion("SHQX between", value1, value2, "shqx");
            return (Criteria) this;
        }

        public Criteria andShqxNotBetween(String value1, String value2) {
            addCriterion("SHQX not between", value1, value2, "shqx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WWJCPT.SYS_ROLE
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}