package com.rabbit.smart.dao.db1.mapper;

import com.rabbit.smart.dao.db1.entity.SysRoleRefMenu;
import com.rabbit.smart.dao.db1.entity.SysRoleRefMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleRefMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE_REF_MENU
     *
     * @mbggenerated
     */
    int countByExample(SysRoleRefMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE_REF_MENU
     *
     * @mbggenerated
     */
    int deleteByExample(SysRoleRefMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE_REF_MENU
     *
     * @mbggenerated
     */
    int insert(SysRoleRefMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE_REF_MENU
     *
     * @mbggenerated
     */
    int insertSelective(SysRoleRefMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE_REF_MENU
     *
     * @mbggenerated
     */
    List<SysRoleRefMenu> selectByExample(SysRoleRefMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE_REF_MENU
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRoleRefMenu record, @Param("example") SysRoleRefMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_ROLE_REF_MENU
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRoleRefMenu record, @Param("example") SysRoleRefMenuExample example);
}