package com.rabbit.smart.dao.mapper;

import com.rabbit.smart.dao.entity.FrmCode;
import com.rabbit.smart.dao.entity.FrmCodeExample;
import com.rabbit.smart.dao.entity.FrmCodeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrmCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_CODE
     *
     * @mbggenerated
     */
    int countByExample(FrmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_CODE
     *
     * @mbggenerated
     */
    int deleteByExample(FrmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_CODE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FrmCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_CODE
     *
     * @mbggenerated
     */
    int insert(FrmCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_CODE
     *
     * @mbggenerated
     */
    int insertSelective(FrmCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_CODE
     *
     * @mbggenerated
     */
    List<FrmCode> selectByExample(FrmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_CODE
     *
     * @mbggenerated
     */
    FrmCode selectByPrimaryKey(FrmCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_CODE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FrmCode record, @Param("example") FrmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_CODE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FrmCode record, @Param("example") FrmCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_CODE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FrmCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_CODE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FrmCode record);
}