package com.rabbit.smart.dao.entity;

public class SysRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_relation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_relation.menuid
     *
     * @mbggenerated
     */
    private Long menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_relation.roleid
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_relation.id
     *
     * @return the value of sys_relation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_relation.id
     *
     * @param id the value for sys_relation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_relation.menuid
     *
     * @return the value of sys_relation.menuid
     *
     * @mbggenerated
     */
    public Long getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_relation.menuid
     *
     * @param menuid the value for sys_relation.menuid
     *
     * @mbggenerated
     */
    public void setMenuid(Long menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_relation.roleid
     *
     * @return the value of sys_relation.roleid
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_relation.roleid
     *
     * @param roleid the value for sys_relation.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}