package com.rabbit.smart.dao.entity;

public class SysDept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.pids
     *
     * @mbggenerated
     */
    private String pids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.simplename
     *
     * @mbggenerated
     */
    private String simplename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.fullname
     *
     * @mbggenerated
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.tips
     *
     * @mbggenerated
     */
    private String tips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.id
     *
     * @return the value of sys_dept.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.id
     *
     * @param id the value for sys_dept.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.num
     *
     * @return the value of sys_dept.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.num
     *
     * @param num the value for sys_dept.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.pid
     *
     * @return the value of sys_dept.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.pid
     *
     * @param pid the value for sys_dept.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.pids
     *
     * @return the value of sys_dept.pids
     *
     * @mbggenerated
     */
    public String getPids() {
        return pids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.pids
     *
     * @param pids the value for sys_dept.pids
     *
     * @mbggenerated
     */
    public void setPids(String pids) {
        this.pids = pids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.simplename
     *
     * @return the value of sys_dept.simplename
     *
     * @mbggenerated
     */
    public String getSimplename() {
        return simplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.simplename
     *
     * @param simplename the value for sys_dept.simplename
     *
     * @mbggenerated
     */
    public void setSimplename(String simplename) {
        this.simplename = simplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.fullname
     *
     * @return the value of sys_dept.fullname
     *
     * @mbggenerated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.fullname
     *
     * @param fullname the value for sys_dept.fullname
     *
     * @mbggenerated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.tips
     *
     * @return the value of sys_dept.tips
     *
     * @mbggenerated
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.tips
     *
     * @param tips the value for sys_dept.tips
     *
     * @mbggenerated
     */
    public void setTips(String tips) {
        this.tips = tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.version
     *
     * @return the value of sys_dept.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.version
     *
     * @param version the value for sys_dept.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}