package com.rabbit.smart.dao.entity;

public class SysOperationLogWithBLOBs extends SysOperationLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.method
     *
     * @mbggenerated
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.method
     *
     * @return the value of sys_operation_log.method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.method
     *
     * @param method the value for sys_operation_log.method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.message
     *
     * @return the value of sys_operation_log.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.message
     *
     * @param message the value for sys_operation_log.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message;
    }
}