package com.rabbit.smart.dao.first.entity;

public class FrmCode extends FrmCodeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.DMSM1
     *
     * @mbggenerated
     */
    private String dmsm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.DMSM2
     *
     * @mbggenerated
     */
    private String dmsm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.DMSM3
     *
     * @mbggenerated
     */
    private String dmsm3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.DMSM4
     *
     * @mbggenerated
     */
    private String dmsm4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.DMSX
     *
     * @mbggenerated
     */
    private String dmsx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.SXH
     *
     * @mbggenerated
     */
    private Short sxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.YWDX
     *
     * @mbggenerated
     */
    private String ywdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.ZT
     *
     * @mbggenerated
     */
    private String zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.LBSM
     *
     * @mbggenerated
     */
    private String lbsm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.DMSM1
     *
     * @return the value of WWJCPT.FRM_CODE.DMSM1
     *
     * @mbggenerated
     */
    public String getDmsm1() {
        return dmsm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.DMSM1
     *
     * @param dmsm1 the value for WWJCPT.FRM_CODE.DMSM1
     *
     * @mbggenerated
     */
    public void setDmsm1(String dmsm1) {
        this.dmsm1 = dmsm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.DMSM2
     *
     * @return the value of WWJCPT.FRM_CODE.DMSM2
     *
     * @mbggenerated
     */
    public String getDmsm2() {
        return dmsm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.DMSM2
     *
     * @param dmsm2 the value for WWJCPT.FRM_CODE.DMSM2
     *
     * @mbggenerated
     */
    public void setDmsm2(String dmsm2) {
        this.dmsm2 = dmsm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.DMSM3
     *
     * @return the value of WWJCPT.FRM_CODE.DMSM3
     *
     * @mbggenerated
     */
    public String getDmsm3() {
        return dmsm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.DMSM3
     *
     * @param dmsm3 the value for WWJCPT.FRM_CODE.DMSM3
     *
     * @mbggenerated
     */
    public void setDmsm3(String dmsm3) {
        this.dmsm3 = dmsm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.DMSM4
     *
     * @return the value of WWJCPT.FRM_CODE.DMSM4
     *
     * @mbggenerated
     */
    public String getDmsm4() {
        return dmsm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.DMSM4
     *
     * @param dmsm4 the value for WWJCPT.FRM_CODE.DMSM4
     *
     * @mbggenerated
     */
    public void setDmsm4(String dmsm4) {
        this.dmsm4 = dmsm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.DMSX
     *
     * @return the value of WWJCPT.FRM_CODE.DMSX
     *
     * @mbggenerated
     */
    public String getDmsx() {
        return dmsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.DMSX
     *
     * @param dmsx the value for WWJCPT.FRM_CODE.DMSX
     *
     * @mbggenerated
     */
    public void setDmsx(String dmsx) {
        this.dmsx = dmsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.SXH
     *
     * @return the value of WWJCPT.FRM_CODE.SXH
     *
     * @mbggenerated
     */
    public Short getSxh() {
        return sxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.SXH
     *
     * @param sxh the value for WWJCPT.FRM_CODE.SXH
     *
     * @mbggenerated
     */
    public void setSxh(Short sxh) {
        this.sxh = sxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.YWDX
     *
     * @return the value of WWJCPT.FRM_CODE.YWDX
     *
     * @mbggenerated
     */
    public String getYwdx() {
        return ywdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.YWDX
     *
     * @param ywdx the value for WWJCPT.FRM_CODE.YWDX
     *
     * @mbggenerated
     */
    public void setYwdx(String ywdx) {
        this.ywdx = ywdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.ZT
     *
     * @return the value of WWJCPT.FRM_CODE.ZT
     *
     * @mbggenerated
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.ZT
     *
     * @param zt the value for WWJCPT.FRM_CODE.ZT
     *
     * @mbggenerated
     */
    public void setZt(String zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.LBSM
     *
     * @return the value of WWJCPT.FRM_CODE.LBSM
     *
     * @mbggenerated
     */
    public String getLbsm() {
        return lbsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.LBSM
     *
     * @param lbsm the value for WWJCPT.FRM_CODE.LBSM
     *
     * @mbggenerated
     */
    public void setLbsm(String lbsm) {
        this.lbsm = lbsm;
    }
}