package com.rabbit.smart.dao.first.entity;

public class FrmCodeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.XTLB
     *
     * @mbggenerated
     */
    private String xtlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.DMLB
     *
     * @mbggenerated
     */
    private String dmlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.FRM_CODE.DMZ
     *
     * @mbggenerated
     */
    private String dmz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.XTLB
     *
     * @return the value of WWJCPT.FRM_CODE.XTLB
     *
     * @mbggenerated
     */
    public String getXtlb() {
        return xtlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.XTLB
     *
     * @param xtlb the value for WWJCPT.FRM_CODE.XTLB
     *
     * @mbggenerated
     */
    public void setXtlb(String xtlb) {
        this.xtlb = xtlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.DMLB
     *
     * @return the value of WWJCPT.FRM_CODE.DMLB
     *
     * @mbggenerated
     */
    public String getDmlb() {
        return dmlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.DMLB
     *
     * @param dmlb the value for WWJCPT.FRM_CODE.DMLB
     *
     * @mbggenerated
     */
    public void setDmlb(String dmlb) {
        this.dmlb = dmlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.FRM_CODE.DMZ
     *
     * @return the value of WWJCPT.FRM_CODE.DMZ
     *
     * @mbggenerated
     */
    public String getDmz() {
        return dmz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.FRM_CODE.DMZ
     *
     * @param dmz the value for WWJCPT.FRM_CODE.DMZ
     *
     * @mbggenerated
     */
    public void setDmz(String dmz) {
        this.dmz = dmz;
    }
}