package com.rabbit.smart.dao.first.entity;

public class SysRoleRefMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_ROLE_REF_MENU.RID
     *
     * @mbggenerated
     */
    private String rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_ROLE_REF_MENU.MID
     *
     * @mbggenerated
     */
    private String mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_ROLE_REF_MENU.RID
     *
     * @return the value of WWJCPT.SYS_ROLE_REF_MENU.RID
     *
     * @mbggenerated
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_ROLE_REF_MENU.RID
     *
     * @param rid the value for WWJCPT.SYS_ROLE_REF_MENU.RID
     *
     * @mbggenerated
     */
    public void setRid(String rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_ROLE_REF_MENU.MID
     *
     * @return the value of WWJCPT.SYS_ROLE_REF_MENU.MID
     *
     * @mbggenerated
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_ROLE_REF_MENU.MID
     *
     * @param mid the value for WWJCPT.SYS_ROLE_REF_MENU.MID
     *
     * @mbggenerated
     */
    public void setMid(String mid) {
        this.mid = mid;
    }
}