package com.rabbit.smart.dao.first.entity;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.YHDH
     *
     * @mbggenerated
     */
    private String yhdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.XM
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.MM
     *
     * @mbggenerated
     */
    private String mm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.GLBM
     *
     * @mbggenerated
     */
    private String glbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.SFZMHM
     *
     * @mbggenerated
     */
    private String sfzmhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.IPKS
     *
     * @mbggenerated
     */
    private String ipks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.IPJS
     *
     * @mbggenerated
     */
    private String ipjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.ZHYXQ
     *
     * @mbggenerated
     */
    private Date zhyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.MMYXQ
     *
     * @mbggenerated
     */
    private Date mmyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.ZT
     *
     * @mbggenerated
     */
    private String zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.ZP
     *
     * @mbggenerated
     */
    private String zp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.CJSJ
     *
     * @mbggenerated
     */
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.SCDLSJ
     *
     * @mbggenerated
     */
    private Date scdlsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.SCDLIP
     *
     * @mbggenerated
     */
    private String scdlip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.CJR
     *
     * @mbggenerated
     */
    private String cjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.RID
     *
     * @mbggenerated
     */
    private String rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.THEME
     *
     * @mbggenerated
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.GZDD
     *
     * @mbggenerated
     */
    private String gzdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.MAP
     *
     * @mbggenerated
     */
    private String map;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.SYEVENT
     *
     * @mbggenerated
     */
    private String syevent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER.CJTEVENT
     *
     * @mbggenerated
     */
    private String cjtevent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.YHDH
     *
     * @return the value of WWJCPT.SYS_USER.YHDH
     *
     * @mbggenerated
     */
    public String getYhdh() {
        return yhdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.YHDH
     *
     * @param yhdh the value for WWJCPT.SYS_USER.YHDH
     *
     * @mbggenerated
     */
    public void setYhdh(String yhdh) {
        this.yhdh = yhdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.XM
     *
     * @return the value of WWJCPT.SYS_USER.XM
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.XM
     *
     * @param xm the value for WWJCPT.SYS_USER.XM
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.MM
     *
     * @return the value of WWJCPT.SYS_USER.MM
     *
     * @mbggenerated
     */
    public String getMm() {
        return mm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.MM
     *
     * @param mm the value for WWJCPT.SYS_USER.MM
     *
     * @mbggenerated
     */
    public void setMm(String mm) {
        this.mm = mm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.GLBM
     *
     * @return the value of WWJCPT.SYS_USER.GLBM
     *
     * @mbggenerated
     */
    public String getGlbm() {
        return glbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.GLBM
     *
     * @param glbm the value for WWJCPT.SYS_USER.GLBM
     *
     * @mbggenerated
     */
    public void setGlbm(String glbm) {
        this.glbm = glbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.SFZMHM
     *
     * @return the value of WWJCPT.SYS_USER.SFZMHM
     *
     * @mbggenerated
     */
    public String getSfzmhm() {
        return sfzmhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.SFZMHM
     *
     * @param sfzmhm the value for WWJCPT.SYS_USER.SFZMHM
     *
     * @mbggenerated
     */
    public void setSfzmhm(String sfzmhm) {
        this.sfzmhm = sfzmhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.IPKS
     *
     * @return the value of WWJCPT.SYS_USER.IPKS
     *
     * @mbggenerated
     */
    public String getIpks() {
        return ipks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.IPKS
     *
     * @param ipks the value for WWJCPT.SYS_USER.IPKS
     *
     * @mbggenerated
     */
    public void setIpks(String ipks) {
        this.ipks = ipks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.IPJS
     *
     * @return the value of WWJCPT.SYS_USER.IPJS
     *
     * @mbggenerated
     */
    public String getIpjs() {
        return ipjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.IPJS
     *
     * @param ipjs the value for WWJCPT.SYS_USER.IPJS
     *
     * @mbggenerated
     */
    public void setIpjs(String ipjs) {
        this.ipjs = ipjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.ZHYXQ
     *
     * @return the value of WWJCPT.SYS_USER.ZHYXQ
     *
     * @mbggenerated
     */
    public Date getZhyxq() {
        return zhyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.ZHYXQ
     *
     * @param zhyxq the value for WWJCPT.SYS_USER.ZHYXQ
     *
     * @mbggenerated
     */
    public void setZhyxq(Date zhyxq) {
        this.zhyxq = zhyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.MMYXQ
     *
     * @return the value of WWJCPT.SYS_USER.MMYXQ
     *
     * @mbggenerated
     */
    public Date getMmyxq() {
        return mmyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.MMYXQ
     *
     * @param mmyxq the value for WWJCPT.SYS_USER.MMYXQ
     *
     * @mbggenerated
     */
    public void setMmyxq(Date mmyxq) {
        this.mmyxq = mmyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.ZT
     *
     * @return the value of WWJCPT.SYS_USER.ZT
     *
     * @mbggenerated
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.ZT
     *
     * @param zt the value for WWJCPT.SYS_USER.ZT
     *
     * @mbggenerated
     */
    public void setZt(String zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.ZP
     *
     * @return the value of WWJCPT.SYS_USER.ZP
     *
     * @mbggenerated
     */
    public String getZp() {
        return zp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.ZP
     *
     * @param zp the value for WWJCPT.SYS_USER.ZP
     *
     * @mbggenerated
     */
    public void setZp(String zp) {
        this.zp = zp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.CJSJ
     *
     * @return the value of WWJCPT.SYS_USER.CJSJ
     *
     * @mbggenerated
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.CJSJ
     *
     * @param cjsj the value for WWJCPT.SYS_USER.CJSJ
     *
     * @mbggenerated
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.SCDLSJ
     *
     * @return the value of WWJCPT.SYS_USER.SCDLSJ
     *
     * @mbggenerated
     */
    public Date getScdlsj() {
        return scdlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.SCDLSJ
     *
     * @param scdlsj the value for WWJCPT.SYS_USER.SCDLSJ
     *
     * @mbggenerated
     */
    public void setScdlsj(Date scdlsj) {
        this.scdlsj = scdlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.SCDLIP
     *
     * @return the value of WWJCPT.SYS_USER.SCDLIP
     *
     * @mbggenerated
     */
    public String getScdlip() {
        return scdlip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.SCDLIP
     *
     * @param scdlip the value for WWJCPT.SYS_USER.SCDLIP
     *
     * @mbggenerated
     */
    public void setScdlip(String scdlip) {
        this.scdlip = scdlip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.CJR
     *
     * @return the value of WWJCPT.SYS_USER.CJR
     *
     * @mbggenerated
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.CJR
     *
     * @param cjr the value for WWJCPT.SYS_USER.CJR
     *
     * @mbggenerated
     */
    public void setCjr(String cjr) {
        this.cjr = cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.RID
     *
     * @return the value of WWJCPT.SYS_USER.RID
     *
     * @mbggenerated
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.RID
     *
     * @param rid the value for WWJCPT.SYS_USER.RID
     *
     * @mbggenerated
     */
    public void setRid(String rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.THEME
     *
     * @return the value of WWJCPT.SYS_USER.THEME
     *
     * @mbggenerated
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.THEME
     *
     * @param theme the value for WWJCPT.SYS_USER.THEME
     *
     * @mbggenerated
     */
    public void setTheme(String theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.GZDD
     *
     * @return the value of WWJCPT.SYS_USER.GZDD
     *
     * @mbggenerated
     */
    public String getGzdd() {
        return gzdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.GZDD
     *
     * @param gzdd the value for WWJCPT.SYS_USER.GZDD
     *
     * @mbggenerated
     */
    public void setGzdd(String gzdd) {
        this.gzdd = gzdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.MAP
     *
     * @return the value of WWJCPT.SYS_USER.MAP
     *
     * @mbggenerated
     */
    public String getMap() {
        return map;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.MAP
     *
     * @param map the value for WWJCPT.SYS_USER.MAP
     *
     * @mbggenerated
     */
    public void setMap(String map) {
        this.map = map;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.SYEVENT
     *
     * @return the value of WWJCPT.SYS_USER.SYEVENT
     *
     * @mbggenerated
     */
    public String getSyevent() {
        return syevent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.SYEVENT
     *
     * @param syevent the value for WWJCPT.SYS_USER.SYEVENT
     *
     * @mbggenerated
     */
    public void setSyevent(String syevent) {
        this.syevent = syevent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER.CJTEVENT
     *
     * @return the value of WWJCPT.SYS_USER.CJTEVENT
     *
     * @mbggenerated
     */
    public String getCjtevent() {
        return cjtevent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER.CJTEVENT
     *
     * @param cjtevent the value for WWJCPT.SYS_USER.CJTEVENT
     *
     * @mbggenerated
     */
    public void setCjtevent(String cjtevent) {
        this.cjtevent = cjtevent;
    }
}