package com.rabbit.smart.dao.first.entity;

import java.util.Date;

public class SysUserLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER_LOG.LOGID
     *
     * @mbggenerated
     */
    private String logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER_LOG.YHDH
     *
     * @mbggenerated
     */
    private String yhdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER_LOG.IP
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER_LOG.OPTYPE
     *
     * @mbggenerated
     */
    private String optype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER_LOG.MODELNAME
     *
     * @mbggenerated
     */
    private String modelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER_LOG.METHODNAME
     *
     * @mbggenerated
     */
    private String methodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER_LOG.METHODDESC
     *
     * @mbggenerated
     */
    private String methoddesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER_LOG.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_USER_LOG.DATETIME
     *
     * @mbggenerated
     */
    private Date datetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER_LOG.LOGID
     *
     * @return the value of WWJCPT.SYS_USER_LOG.LOGID
     *
     * @mbggenerated
     */
    public String getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER_LOG.LOGID
     *
     * @param logid the value for WWJCPT.SYS_USER_LOG.LOGID
     *
     * @mbggenerated
     */
    public void setLogid(String logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER_LOG.YHDH
     *
     * @return the value of WWJCPT.SYS_USER_LOG.YHDH
     *
     * @mbggenerated
     */
    public String getYhdh() {
        return yhdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER_LOG.YHDH
     *
     * @param yhdh the value for WWJCPT.SYS_USER_LOG.YHDH
     *
     * @mbggenerated
     */
    public void setYhdh(String yhdh) {
        this.yhdh = yhdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER_LOG.IP
     *
     * @return the value of WWJCPT.SYS_USER_LOG.IP
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER_LOG.IP
     *
     * @param ip the value for WWJCPT.SYS_USER_LOG.IP
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER_LOG.OPTYPE
     *
     * @return the value of WWJCPT.SYS_USER_LOG.OPTYPE
     *
     * @mbggenerated
     */
    public String getOptype() {
        return optype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER_LOG.OPTYPE
     *
     * @param optype the value for WWJCPT.SYS_USER_LOG.OPTYPE
     *
     * @mbggenerated
     */
    public void setOptype(String optype) {
        this.optype = optype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER_LOG.MODELNAME
     *
     * @return the value of WWJCPT.SYS_USER_LOG.MODELNAME
     *
     * @mbggenerated
     */
    public String getModelname() {
        return modelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER_LOG.MODELNAME
     *
     * @param modelname the value for WWJCPT.SYS_USER_LOG.MODELNAME
     *
     * @mbggenerated
     */
    public void setModelname(String modelname) {
        this.modelname = modelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER_LOG.METHODNAME
     *
     * @return the value of WWJCPT.SYS_USER_LOG.METHODNAME
     *
     * @mbggenerated
     */
    public String getMethodname() {
        return methodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER_LOG.METHODNAME
     *
     * @param methodname the value for WWJCPT.SYS_USER_LOG.METHODNAME
     *
     * @mbggenerated
     */
    public void setMethodname(String methodname) {
        this.methodname = methodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER_LOG.METHODDESC
     *
     * @return the value of WWJCPT.SYS_USER_LOG.METHODDESC
     *
     * @mbggenerated
     */
    public String getMethoddesc() {
        return methoddesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER_LOG.METHODDESC
     *
     * @param methoddesc the value for WWJCPT.SYS_USER_LOG.METHODDESC
     *
     * @mbggenerated
     */
    public void setMethoddesc(String methoddesc) {
        this.methoddesc = methoddesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER_LOG.URL
     *
     * @return the value of WWJCPT.SYS_USER_LOG.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER_LOG.URL
     *
     * @param url the value for WWJCPT.SYS_USER_LOG.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_USER_LOG.DATETIME
     *
     * @return the value of WWJCPT.SYS_USER_LOG.DATETIME
     *
     * @mbggenerated
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_USER_LOG.DATETIME
     *
     * @param datetime the value for WWJCPT.SYS_USER_LOG.DATETIME
     *
     * @mbggenerated
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
}