package com.rabbit.smart.dao.first.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    public SysUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andYhdhIsNull() {
            addCriterion("YHDH is null");
            return (Criteria) this;
        }

        public Criteria andYhdhIsNotNull() {
            addCriterion("YHDH is not null");
            return (Criteria) this;
        }

        public Criteria andYhdhEqualTo(String value) {
            addCriterion("YHDH =", value, "yhdh");
            return (Criteria) this;
        }

        public Criteria andYhdhNotEqualTo(String value) {
            addCriterion("YHDH <>", value, "yhdh");
            return (Criteria) this;
        }

        public Criteria andYhdhGreaterThan(String value) {
            addCriterion("YHDH >", value, "yhdh");
            return (Criteria) this;
        }

        public Criteria andYhdhGreaterThanOrEqualTo(String value) {
            addCriterion("YHDH >=", value, "yhdh");
            return (Criteria) this;
        }

        public Criteria andYhdhLessThan(String value) {
            addCriterion("YHDH <", value, "yhdh");
            return (Criteria) this;
        }

        public Criteria andYhdhLessThanOrEqualTo(String value) {
            addCriterion("YHDH <=", value, "yhdh");
            return (Criteria) this;
        }

        public Criteria andYhdhLike(String value) {
            addCriterion("YHDH like", value, "yhdh");
            return (Criteria) this;
        }

        public Criteria andYhdhNotLike(String value) {
            addCriterion("YHDH not like", value, "yhdh");
            return (Criteria) this;
        }

        public Criteria andYhdhIn(List<String> values) {
            addCriterion("YHDH in", values, "yhdh");
            return (Criteria) this;
        }

        public Criteria andYhdhNotIn(List<String> values) {
            addCriterion("YHDH not in", values, "yhdh");
            return (Criteria) this;
        }

        public Criteria andYhdhBetween(String value1, String value2) {
            addCriterion("YHDH between", value1, value2, "yhdh");
            return (Criteria) this;
        }

        public Criteria andYhdhNotBetween(String value1, String value2) {
            addCriterion("YHDH not between", value1, value2, "yhdh");
            return (Criteria) this;
        }

        public Criteria andXmIsNull() {
            addCriterion("XM is null");
            return (Criteria) this;
        }

        public Criteria andXmIsNotNull() {
            addCriterion("XM is not null");
            return (Criteria) this;
        }

        public Criteria andXmEqualTo(String value) {
            addCriterion("XM =", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotEqualTo(String value) {
            addCriterion("XM <>", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmGreaterThan(String value) {
            addCriterion("XM >", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmGreaterThanOrEqualTo(String value) {
            addCriterion("XM >=", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLessThan(String value) {
            addCriterion("XM <", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLessThanOrEqualTo(String value) {
            addCriterion("XM <=", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLike(String value) {
            addCriterion("XM like", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotLike(String value) {
            addCriterion("XM not like", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmIn(List<String> values) {
            addCriterion("XM in", values, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotIn(List<String> values) {
            addCriterion("XM not in", values, "xm");
            return (Criteria) this;
        }

        public Criteria andXmBetween(String value1, String value2) {
            addCriterion("XM between", value1, value2, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotBetween(String value1, String value2) {
            addCriterion("XM not between", value1, value2, "xm");
            return (Criteria) this;
        }

        public Criteria andMmIsNull() {
            addCriterion("MM is null");
            return (Criteria) this;
        }

        public Criteria andMmIsNotNull() {
            addCriterion("MM is not null");
            return (Criteria) this;
        }

        public Criteria andMmEqualTo(String value) {
            addCriterion("MM =", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmNotEqualTo(String value) {
            addCriterion("MM <>", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmGreaterThan(String value) {
            addCriterion("MM >", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmGreaterThanOrEqualTo(String value) {
            addCriterion("MM >=", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmLessThan(String value) {
            addCriterion("MM <", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmLessThanOrEqualTo(String value) {
            addCriterion("MM <=", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmLike(String value) {
            addCriterion("MM like", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmNotLike(String value) {
            addCriterion("MM not like", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmIn(List<String> values) {
            addCriterion("MM in", values, "mm");
            return (Criteria) this;
        }

        public Criteria andMmNotIn(List<String> values) {
            addCriterion("MM not in", values, "mm");
            return (Criteria) this;
        }

        public Criteria andMmBetween(String value1, String value2) {
            addCriterion("MM between", value1, value2, "mm");
            return (Criteria) this;
        }

        public Criteria andMmNotBetween(String value1, String value2) {
            addCriterion("MM not between", value1, value2, "mm");
            return (Criteria) this;
        }

        public Criteria andGlbmIsNull() {
            addCriterion("GLBM is null");
            return (Criteria) this;
        }

        public Criteria andGlbmIsNotNull() {
            addCriterion("GLBM is not null");
            return (Criteria) this;
        }

        public Criteria andGlbmEqualTo(String value) {
            addCriterion("GLBM =", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmNotEqualTo(String value) {
            addCriterion("GLBM <>", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmGreaterThan(String value) {
            addCriterion("GLBM >", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmGreaterThanOrEqualTo(String value) {
            addCriterion("GLBM >=", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmLessThan(String value) {
            addCriterion("GLBM <", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmLessThanOrEqualTo(String value) {
            addCriterion("GLBM <=", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmLike(String value) {
            addCriterion("GLBM like", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmNotLike(String value) {
            addCriterion("GLBM not like", value, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmIn(List<String> values) {
            addCriterion("GLBM in", values, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmNotIn(List<String> values) {
            addCriterion("GLBM not in", values, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmBetween(String value1, String value2) {
            addCriterion("GLBM between", value1, value2, "glbm");
            return (Criteria) this;
        }

        public Criteria andGlbmNotBetween(String value1, String value2) {
            addCriterion("GLBM not between", value1, value2, "glbm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmIsNull() {
            addCriterion("SFZMHM is null");
            return (Criteria) this;
        }

        public Criteria andSfzmhmIsNotNull() {
            addCriterion("SFZMHM is not null");
            return (Criteria) this;
        }

        public Criteria andSfzmhmEqualTo(String value) {
            addCriterion("SFZMHM =", value, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmNotEqualTo(String value) {
            addCriterion("SFZMHM <>", value, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmGreaterThan(String value) {
            addCriterion("SFZMHM >", value, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmGreaterThanOrEqualTo(String value) {
            addCriterion("SFZMHM >=", value, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmLessThan(String value) {
            addCriterion("SFZMHM <", value, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmLessThanOrEqualTo(String value) {
            addCriterion("SFZMHM <=", value, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmLike(String value) {
            addCriterion("SFZMHM like", value, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmNotLike(String value) {
            addCriterion("SFZMHM not like", value, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmIn(List<String> values) {
            addCriterion("SFZMHM in", values, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmNotIn(List<String> values) {
            addCriterion("SFZMHM not in", values, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmBetween(String value1, String value2) {
            addCriterion("SFZMHM between", value1, value2, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andSfzmhmNotBetween(String value1, String value2) {
            addCriterion("SFZMHM not between", value1, value2, "sfzmhm");
            return (Criteria) this;
        }

        public Criteria andIpksIsNull() {
            addCriterion("IPKS is null");
            return (Criteria) this;
        }

        public Criteria andIpksIsNotNull() {
            addCriterion("IPKS is not null");
            return (Criteria) this;
        }

        public Criteria andIpksEqualTo(String value) {
            addCriterion("IPKS =", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksNotEqualTo(String value) {
            addCriterion("IPKS <>", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksGreaterThan(String value) {
            addCriterion("IPKS >", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksGreaterThanOrEqualTo(String value) {
            addCriterion("IPKS >=", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksLessThan(String value) {
            addCriterion("IPKS <", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksLessThanOrEqualTo(String value) {
            addCriterion("IPKS <=", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksLike(String value) {
            addCriterion("IPKS like", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksNotLike(String value) {
            addCriterion("IPKS not like", value, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksIn(List<String> values) {
            addCriterion("IPKS in", values, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksNotIn(List<String> values) {
            addCriterion("IPKS not in", values, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksBetween(String value1, String value2) {
            addCriterion("IPKS between", value1, value2, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpksNotBetween(String value1, String value2) {
            addCriterion("IPKS not between", value1, value2, "ipks");
            return (Criteria) this;
        }

        public Criteria andIpjsIsNull() {
            addCriterion("IPJS is null");
            return (Criteria) this;
        }

        public Criteria andIpjsIsNotNull() {
            addCriterion("IPJS is not null");
            return (Criteria) this;
        }

        public Criteria andIpjsEqualTo(String value) {
            addCriterion("IPJS =", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsNotEqualTo(String value) {
            addCriterion("IPJS <>", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsGreaterThan(String value) {
            addCriterion("IPJS >", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsGreaterThanOrEqualTo(String value) {
            addCriterion("IPJS >=", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsLessThan(String value) {
            addCriterion("IPJS <", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsLessThanOrEqualTo(String value) {
            addCriterion("IPJS <=", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsLike(String value) {
            addCriterion("IPJS like", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsNotLike(String value) {
            addCriterion("IPJS not like", value, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsIn(List<String> values) {
            addCriterion("IPJS in", values, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsNotIn(List<String> values) {
            addCriterion("IPJS not in", values, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsBetween(String value1, String value2) {
            addCriterion("IPJS between", value1, value2, "ipjs");
            return (Criteria) this;
        }

        public Criteria andIpjsNotBetween(String value1, String value2) {
            addCriterion("IPJS not between", value1, value2, "ipjs");
            return (Criteria) this;
        }

        public Criteria andZhyxqIsNull() {
            addCriterion("ZHYXQ is null");
            return (Criteria) this;
        }

        public Criteria andZhyxqIsNotNull() {
            addCriterion("ZHYXQ is not null");
            return (Criteria) this;
        }

        public Criteria andZhyxqEqualTo(Date value) {
            addCriterion("ZHYXQ =", value, "zhyxq");
            return (Criteria) this;
        }

        public Criteria andZhyxqNotEqualTo(Date value) {
            addCriterion("ZHYXQ <>", value, "zhyxq");
            return (Criteria) this;
        }

        public Criteria andZhyxqGreaterThan(Date value) {
            addCriterion("ZHYXQ >", value, "zhyxq");
            return (Criteria) this;
        }

        public Criteria andZhyxqGreaterThanOrEqualTo(Date value) {
            addCriterion("ZHYXQ >=", value, "zhyxq");
            return (Criteria) this;
        }

        public Criteria andZhyxqLessThan(Date value) {
            addCriterion("ZHYXQ <", value, "zhyxq");
            return (Criteria) this;
        }

        public Criteria andZhyxqLessThanOrEqualTo(Date value) {
            addCriterion("ZHYXQ <=", value, "zhyxq");
            return (Criteria) this;
        }

        public Criteria andZhyxqIn(List<Date> values) {
            addCriterion("ZHYXQ in", values, "zhyxq");
            return (Criteria) this;
        }

        public Criteria andZhyxqNotIn(List<Date> values) {
            addCriterion("ZHYXQ not in", values, "zhyxq");
            return (Criteria) this;
        }

        public Criteria andZhyxqBetween(Date value1, Date value2) {
            addCriterion("ZHYXQ between", value1, value2, "zhyxq");
            return (Criteria) this;
        }

        public Criteria andZhyxqNotBetween(Date value1, Date value2) {
            addCriterion("ZHYXQ not between", value1, value2, "zhyxq");
            return (Criteria) this;
        }

        public Criteria andMmyxqIsNull() {
            addCriterion("MMYXQ is null");
            return (Criteria) this;
        }

        public Criteria andMmyxqIsNotNull() {
            addCriterion("MMYXQ is not null");
            return (Criteria) this;
        }

        public Criteria andMmyxqEqualTo(Date value) {
            addCriterion("MMYXQ =", value, "mmyxq");
            return (Criteria) this;
        }

        public Criteria andMmyxqNotEqualTo(Date value) {
            addCriterion("MMYXQ <>", value, "mmyxq");
            return (Criteria) this;
        }

        public Criteria andMmyxqGreaterThan(Date value) {
            addCriterion("MMYXQ >", value, "mmyxq");
            return (Criteria) this;
        }

        public Criteria andMmyxqGreaterThanOrEqualTo(Date value) {
            addCriterion("MMYXQ >=", value, "mmyxq");
            return (Criteria) this;
        }

        public Criteria andMmyxqLessThan(Date value) {
            addCriterion("MMYXQ <", value, "mmyxq");
            return (Criteria) this;
        }

        public Criteria andMmyxqLessThanOrEqualTo(Date value) {
            addCriterion("MMYXQ <=", value, "mmyxq");
            return (Criteria) this;
        }

        public Criteria andMmyxqIn(List<Date> values) {
            addCriterion("MMYXQ in", values, "mmyxq");
            return (Criteria) this;
        }

        public Criteria andMmyxqNotIn(List<Date> values) {
            addCriterion("MMYXQ not in", values, "mmyxq");
            return (Criteria) this;
        }

        public Criteria andMmyxqBetween(Date value1, Date value2) {
            addCriterion("MMYXQ between", value1, value2, "mmyxq");
            return (Criteria) this;
        }

        public Criteria andMmyxqNotBetween(Date value1, Date value2) {
            addCriterion("MMYXQ not between", value1, value2, "mmyxq");
            return (Criteria) this;
        }

        public Criteria andZtIsNull() {
            addCriterion("ZT is null");
            return (Criteria) this;
        }

        public Criteria andZtIsNotNull() {
            addCriterion("ZT is not null");
            return (Criteria) this;
        }

        public Criteria andZtEqualTo(String value) {
            addCriterion("ZT =", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotEqualTo(String value) {
            addCriterion("ZT <>", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtGreaterThan(String value) {
            addCriterion("ZT >", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtGreaterThanOrEqualTo(String value) {
            addCriterion("ZT >=", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtLessThan(String value) {
            addCriterion("ZT <", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtLessThanOrEqualTo(String value) {
            addCriterion("ZT <=", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtLike(String value) {
            addCriterion("ZT like", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotLike(String value) {
            addCriterion("ZT not like", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtIn(List<String> values) {
            addCriterion("ZT in", values, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotIn(List<String> values) {
            addCriterion("ZT not in", values, "zt");
            return (Criteria) this;
        }

        public Criteria andZtBetween(String value1, String value2) {
            addCriterion("ZT between", value1, value2, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotBetween(String value1, String value2) {
            addCriterion("ZT not between", value1, value2, "zt");
            return (Criteria) this;
        }

        public Criteria andZpIsNull() {
            addCriterion("ZP is null");
            return (Criteria) this;
        }

        public Criteria andZpIsNotNull() {
            addCriterion("ZP is not null");
            return (Criteria) this;
        }

        public Criteria andZpEqualTo(String value) {
            addCriterion("ZP =", value, "zp");
            return (Criteria) this;
        }

        public Criteria andZpNotEqualTo(String value) {
            addCriterion("ZP <>", value, "zp");
            return (Criteria) this;
        }

        public Criteria andZpGreaterThan(String value) {
            addCriterion("ZP >", value, "zp");
            return (Criteria) this;
        }

        public Criteria andZpGreaterThanOrEqualTo(String value) {
            addCriterion("ZP >=", value, "zp");
            return (Criteria) this;
        }

        public Criteria andZpLessThan(String value) {
            addCriterion("ZP <", value, "zp");
            return (Criteria) this;
        }

        public Criteria andZpLessThanOrEqualTo(String value) {
            addCriterion("ZP <=", value, "zp");
            return (Criteria) this;
        }

        public Criteria andZpLike(String value) {
            addCriterion("ZP like", value, "zp");
            return (Criteria) this;
        }

        public Criteria andZpNotLike(String value) {
            addCriterion("ZP not like", value, "zp");
            return (Criteria) this;
        }

        public Criteria andZpIn(List<String> values) {
            addCriterion("ZP in", values, "zp");
            return (Criteria) this;
        }

        public Criteria andZpNotIn(List<String> values) {
            addCriterion("ZP not in", values, "zp");
            return (Criteria) this;
        }

        public Criteria andZpBetween(String value1, String value2) {
            addCriterion("ZP between", value1, value2, "zp");
            return (Criteria) this;
        }

        public Criteria andZpNotBetween(String value1, String value2) {
            addCriterion("ZP not between", value1, value2, "zp");
            return (Criteria) this;
        }

        public Criteria andCjsjIsNull() {
            addCriterion("CJSJ is null");
            return (Criteria) this;
        }

        public Criteria andCjsjIsNotNull() {
            addCriterion("CJSJ is not null");
            return (Criteria) this;
        }

        public Criteria andCjsjEqualTo(Date value) {
            addCriterion("CJSJ =", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotEqualTo(Date value) {
            addCriterion("CJSJ <>", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjGreaterThan(Date value) {
            addCriterion("CJSJ >", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjGreaterThanOrEqualTo(Date value) {
            addCriterion("CJSJ >=", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjLessThan(Date value) {
            addCriterion("CJSJ <", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjLessThanOrEqualTo(Date value) {
            addCriterion("CJSJ <=", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjIn(List<Date> values) {
            addCriterion("CJSJ in", values, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotIn(List<Date> values) {
            addCriterion("CJSJ not in", values, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjBetween(Date value1, Date value2) {
            addCriterion("CJSJ between", value1, value2, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotBetween(Date value1, Date value2) {
            addCriterion("CJSJ not between", value1, value2, "cjsj");
            return (Criteria) this;
        }

        public Criteria andScdlsjIsNull() {
            addCriterion("SCDLSJ is null");
            return (Criteria) this;
        }

        public Criteria andScdlsjIsNotNull() {
            addCriterion("SCDLSJ is not null");
            return (Criteria) this;
        }

        public Criteria andScdlsjEqualTo(Date value) {
            addCriterion("SCDLSJ =", value, "scdlsj");
            return (Criteria) this;
        }

        public Criteria andScdlsjNotEqualTo(Date value) {
            addCriterion("SCDLSJ <>", value, "scdlsj");
            return (Criteria) this;
        }

        public Criteria andScdlsjGreaterThan(Date value) {
            addCriterion("SCDLSJ >", value, "scdlsj");
            return (Criteria) this;
        }

        public Criteria andScdlsjGreaterThanOrEqualTo(Date value) {
            addCriterion("SCDLSJ >=", value, "scdlsj");
            return (Criteria) this;
        }

        public Criteria andScdlsjLessThan(Date value) {
            addCriterion("SCDLSJ <", value, "scdlsj");
            return (Criteria) this;
        }

        public Criteria andScdlsjLessThanOrEqualTo(Date value) {
            addCriterion("SCDLSJ <=", value, "scdlsj");
            return (Criteria) this;
        }

        public Criteria andScdlsjIn(List<Date> values) {
            addCriterion("SCDLSJ in", values, "scdlsj");
            return (Criteria) this;
        }

        public Criteria andScdlsjNotIn(List<Date> values) {
            addCriterion("SCDLSJ not in", values, "scdlsj");
            return (Criteria) this;
        }

        public Criteria andScdlsjBetween(Date value1, Date value2) {
            addCriterion("SCDLSJ between", value1, value2, "scdlsj");
            return (Criteria) this;
        }

        public Criteria andScdlsjNotBetween(Date value1, Date value2) {
            addCriterion("SCDLSJ not between", value1, value2, "scdlsj");
            return (Criteria) this;
        }

        public Criteria andScdlipIsNull() {
            addCriterion("SCDLIP is null");
            return (Criteria) this;
        }

        public Criteria andScdlipIsNotNull() {
            addCriterion("SCDLIP is not null");
            return (Criteria) this;
        }

        public Criteria andScdlipEqualTo(String value) {
            addCriterion("SCDLIP =", value, "scdlip");
            return (Criteria) this;
        }

        public Criteria andScdlipNotEqualTo(String value) {
            addCriterion("SCDLIP <>", value, "scdlip");
            return (Criteria) this;
        }

        public Criteria andScdlipGreaterThan(String value) {
            addCriterion("SCDLIP >", value, "scdlip");
            return (Criteria) this;
        }

        public Criteria andScdlipGreaterThanOrEqualTo(String value) {
            addCriterion("SCDLIP >=", value, "scdlip");
            return (Criteria) this;
        }

        public Criteria andScdlipLessThan(String value) {
            addCriterion("SCDLIP <", value, "scdlip");
            return (Criteria) this;
        }

        public Criteria andScdlipLessThanOrEqualTo(String value) {
            addCriterion("SCDLIP <=", value, "scdlip");
            return (Criteria) this;
        }

        public Criteria andScdlipLike(String value) {
            addCriterion("SCDLIP like", value, "scdlip");
            return (Criteria) this;
        }

        public Criteria andScdlipNotLike(String value) {
            addCriterion("SCDLIP not like", value, "scdlip");
            return (Criteria) this;
        }

        public Criteria andScdlipIn(List<String> values) {
            addCriterion("SCDLIP in", values, "scdlip");
            return (Criteria) this;
        }

        public Criteria andScdlipNotIn(List<String> values) {
            addCriterion("SCDLIP not in", values, "scdlip");
            return (Criteria) this;
        }

        public Criteria andScdlipBetween(String value1, String value2) {
            addCriterion("SCDLIP between", value1, value2, "scdlip");
            return (Criteria) this;
        }

        public Criteria andScdlipNotBetween(String value1, String value2) {
            addCriterion("SCDLIP not between", value1, value2, "scdlip");
            return (Criteria) this;
        }

        public Criteria andCjrIsNull() {
            addCriterion("CJR is null");
            return (Criteria) this;
        }

        public Criteria andCjrIsNotNull() {
            addCriterion("CJR is not null");
            return (Criteria) this;
        }

        public Criteria andCjrEqualTo(String value) {
            addCriterion("CJR =", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotEqualTo(String value) {
            addCriterion("CJR <>", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrGreaterThan(String value) {
            addCriterion("CJR >", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrGreaterThanOrEqualTo(String value) {
            addCriterion("CJR >=", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLessThan(String value) {
            addCriterion("CJR <", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLessThanOrEqualTo(String value) {
            addCriterion("CJR <=", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLike(String value) {
            addCriterion("CJR like", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotLike(String value) {
            addCriterion("CJR not like", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrIn(List<String> values) {
            addCriterion("CJR in", values, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotIn(List<String> values) {
            addCriterion("CJR not in", values, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrBetween(String value1, String value2) {
            addCriterion("CJR between", value1, value2, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotBetween(String value1, String value2) {
            addCriterion("CJR not between", value1, value2, "cjr");
            return (Criteria) this;
        }

        public Criteria andRidIsNull() {
            addCriterion("RID is null");
            return (Criteria) this;
        }

        public Criteria andRidIsNotNull() {
            addCriterion("RID is not null");
            return (Criteria) this;
        }

        public Criteria andRidEqualTo(String value) {
            addCriterion("RID =", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotEqualTo(String value) {
            addCriterion("RID <>", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThan(String value) {
            addCriterion("RID >", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThanOrEqualTo(String value) {
            addCriterion("RID >=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThan(String value) {
            addCriterion("RID <", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThanOrEqualTo(String value) {
            addCriterion("RID <=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLike(String value) {
            addCriterion("RID like", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotLike(String value) {
            addCriterion("RID not like", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidIn(List<String> values) {
            addCriterion("RID in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotIn(List<String> values) {
            addCriterion("RID not in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidBetween(String value1, String value2) {
            addCriterion("RID between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotBetween(String value1, String value2) {
            addCriterion("RID not between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andThemeIsNull() {
            addCriterion("THEME is null");
            return (Criteria) this;
        }

        public Criteria andThemeIsNotNull() {
            addCriterion("THEME is not null");
            return (Criteria) this;
        }

        public Criteria andThemeEqualTo(String value) {
            addCriterion("THEME =", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotEqualTo(String value) {
            addCriterion("THEME <>", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeGreaterThan(String value) {
            addCriterion("THEME >", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeGreaterThanOrEqualTo(String value) {
            addCriterion("THEME >=", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeLessThan(String value) {
            addCriterion("THEME <", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeLessThanOrEqualTo(String value) {
            addCriterion("THEME <=", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeLike(String value) {
            addCriterion("THEME like", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotLike(String value) {
            addCriterion("THEME not like", value, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeIn(List<String> values) {
            addCriterion("THEME in", values, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotIn(List<String> values) {
            addCriterion("THEME not in", values, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeBetween(String value1, String value2) {
            addCriterion("THEME between", value1, value2, "theme");
            return (Criteria) this;
        }

        public Criteria andThemeNotBetween(String value1, String value2) {
            addCriterion("THEME not between", value1, value2, "theme");
            return (Criteria) this;
        }

        public Criteria andGzddIsNull() {
            addCriterion("GZDD is null");
            return (Criteria) this;
        }

        public Criteria andGzddIsNotNull() {
            addCriterion("GZDD is not null");
            return (Criteria) this;
        }

        public Criteria andGzddEqualTo(String value) {
            addCriterion("GZDD =", value, "gzdd");
            return (Criteria) this;
        }

        public Criteria andGzddNotEqualTo(String value) {
            addCriterion("GZDD <>", value, "gzdd");
            return (Criteria) this;
        }

        public Criteria andGzddGreaterThan(String value) {
            addCriterion("GZDD >", value, "gzdd");
            return (Criteria) this;
        }

        public Criteria andGzddGreaterThanOrEqualTo(String value) {
            addCriterion("GZDD >=", value, "gzdd");
            return (Criteria) this;
        }

        public Criteria andGzddLessThan(String value) {
            addCriterion("GZDD <", value, "gzdd");
            return (Criteria) this;
        }

        public Criteria andGzddLessThanOrEqualTo(String value) {
            addCriterion("GZDD <=", value, "gzdd");
            return (Criteria) this;
        }

        public Criteria andGzddLike(String value) {
            addCriterion("GZDD like", value, "gzdd");
            return (Criteria) this;
        }

        public Criteria andGzddNotLike(String value) {
            addCriterion("GZDD not like", value, "gzdd");
            return (Criteria) this;
        }

        public Criteria andGzddIn(List<String> values) {
            addCriterion("GZDD in", values, "gzdd");
            return (Criteria) this;
        }

        public Criteria andGzddNotIn(List<String> values) {
            addCriterion("GZDD not in", values, "gzdd");
            return (Criteria) this;
        }

        public Criteria andGzddBetween(String value1, String value2) {
            addCriterion("GZDD between", value1, value2, "gzdd");
            return (Criteria) this;
        }

        public Criteria andGzddNotBetween(String value1, String value2) {
            addCriterion("GZDD not between", value1, value2, "gzdd");
            return (Criteria) this;
        }

        public Criteria andMapIsNull() {
            addCriterion("MAP is null");
            return (Criteria) this;
        }

        public Criteria andMapIsNotNull() {
            addCriterion("MAP is not null");
            return (Criteria) this;
        }

        public Criteria andMapEqualTo(String value) {
            addCriterion("MAP =", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapNotEqualTo(String value) {
            addCriterion("MAP <>", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapGreaterThan(String value) {
            addCriterion("MAP >", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapGreaterThanOrEqualTo(String value) {
            addCriterion("MAP >=", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapLessThan(String value) {
            addCriterion("MAP <", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapLessThanOrEqualTo(String value) {
            addCriterion("MAP <=", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapLike(String value) {
            addCriterion("MAP like", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapNotLike(String value) {
            addCriterion("MAP not like", value, "map");
            return (Criteria) this;
        }

        public Criteria andMapIn(List<String> values) {
            addCriterion("MAP in", values, "map");
            return (Criteria) this;
        }

        public Criteria andMapNotIn(List<String> values) {
            addCriterion("MAP not in", values, "map");
            return (Criteria) this;
        }

        public Criteria andMapBetween(String value1, String value2) {
            addCriterion("MAP between", value1, value2, "map");
            return (Criteria) this;
        }

        public Criteria andMapNotBetween(String value1, String value2) {
            addCriterion("MAP not between", value1, value2, "map");
            return (Criteria) this;
        }

        public Criteria andSyeventIsNull() {
            addCriterion("SYEVENT is null");
            return (Criteria) this;
        }

        public Criteria andSyeventIsNotNull() {
            addCriterion("SYEVENT is not null");
            return (Criteria) this;
        }

        public Criteria andSyeventEqualTo(String value) {
            addCriterion("SYEVENT =", value, "syevent");
            return (Criteria) this;
        }

        public Criteria andSyeventNotEqualTo(String value) {
            addCriterion("SYEVENT <>", value, "syevent");
            return (Criteria) this;
        }

        public Criteria andSyeventGreaterThan(String value) {
            addCriterion("SYEVENT >", value, "syevent");
            return (Criteria) this;
        }

        public Criteria andSyeventGreaterThanOrEqualTo(String value) {
            addCriterion("SYEVENT >=", value, "syevent");
            return (Criteria) this;
        }

        public Criteria andSyeventLessThan(String value) {
            addCriterion("SYEVENT <", value, "syevent");
            return (Criteria) this;
        }

        public Criteria andSyeventLessThanOrEqualTo(String value) {
            addCriterion("SYEVENT <=", value, "syevent");
            return (Criteria) this;
        }

        public Criteria andSyeventLike(String value) {
            addCriterion("SYEVENT like", value, "syevent");
            return (Criteria) this;
        }

        public Criteria andSyeventNotLike(String value) {
            addCriterion("SYEVENT not like", value, "syevent");
            return (Criteria) this;
        }

        public Criteria andSyeventIn(List<String> values) {
            addCriterion("SYEVENT in", values, "syevent");
            return (Criteria) this;
        }

        public Criteria andSyeventNotIn(List<String> values) {
            addCriterion("SYEVENT not in", values, "syevent");
            return (Criteria) this;
        }

        public Criteria andSyeventBetween(String value1, String value2) {
            addCriterion("SYEVENT between", value1, value2, "syevent");
            return (Criteria) this;
        }

        public Criteria andSyeventNotBetween(String value1, String value2) {
            addCriterion("SYEVENT not between", value1, value2, "syevent");
            return (Criteria) this;
        }

        public Criteria andCjteventIsNull() {
            addCriterion("CJTEVENT is null");
            return (Criteria) this;
        }

        public Criteria andCjteventIsNotNull() {
            addCriterion("CJTEVENT is not null");
            return (Criteria) this;
        }

        public Criteria andCjteventEqualTo(String value) {
            addCriterion("CJTEVENT =", value, "cjtevent");
            return (Criteria) this;
        }

        public Criteria andCjteventNotEqualTo(String value) {
            addCriterion("CJTEVENT <>", value, "cjtevent");
            return (Criteria) this;
        }

        public Criteria andCjteventGreaterThan(String value) {
            addCriterion("CJTEVENT >", value, "cjtevent");
            return (Criteria) this;
        }

        public Criteria andCjteventGreaterThanOrEqualTo(String value) {
            addCriterion("CJTEVENT >=", value, "cjtevent");
            return (Criteria) this;
        }

        public Criteria andCjteventLessThan(String value) {
            addCriterion("CJTEVENT <", value, "cjtevent");
            return (Criteria) this;
        }

        public Criteria andCjteventLessThanOrEqualTo(String value) {
            addCriterion("CJTEVENT <=", value, "cjtevent");
            return (Criteria) this;
        }

        public Criteria andCjteventLike(String value) {
            addCriterion("CJTEVENT like", value, "cjtevent");
            return (Criteria) this;
        }

        public Criteria andCjteventNotLike(String value) {
            addCriterion("CJTEVENT not like", value, "cjtevent");
            return (Criteria) this;
        }

        public Criteria andCjteventIn(List<String> values) {
            addCriterion("CJTEVENT in", values, "cjtevent");
            return (Criteria) this;
        }

        public Criteria andCjteventNotIn(List<String> values) {
            addCriterion("CJTEVENT not in", values, "cjtevent");
            return (Criteria) this;
        }

        public Criteria andCjteventBetween(String value1, String value2) {
            addCriterion("CJTEVENT between", value1, value2, "cjtevent");
            return (Criteria) this;
        }

        public Criteria andCjteventNotBetween(String value1, String value2) {
            addCriterion("CJTEVENT not between", value1, value2, "cjtevent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}