package com.rabbit.smart.dao.mapper;

import com.rabbit.smart.dao.entity.SysRelation;
import com.rabbit.smart.dao.entity.SysRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbggenerated
     */
    int countByExample(SysRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbggenerated
     */
    int deleteByExample(SysRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbggenerated
     */
    int insert(SysRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbggenerated
     */
    int insertSelective(SysRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbggenerated
     */
    List<SysRelation> selectByExample(SysRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbggenerated
     */
    SysRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRelation record, @Param("example") SysRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRelation record, @Param("example") SysRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRelation record);
}