package com.rabbit.smart.dao.db2.entity;

public class XhxtCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UTCDBA.XHXT_CODE.NCODETYPEID
     *
     * @mbggenerated
     */
    private Short ncodetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UTCDBA.XHXT_CODE.CCODEVALUE
     *
     * @mbggenerated
     */
    private String ccodevalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UTCDBA.XHXT_CODE.CCODEVALUENOTE
     *
     * @mbggenerated
     */
    private String ccodevaluenote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UTCDBA.XHXT_CODE.NCODETYPEID
     *
     * @return the value of UTCDBA.XHXT_CODE.NCODETYPEID
     *
     * @mbggenerated
     */
    public Short getNcodetypeid() {
        return ncodetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UTCDBA.XHXT_CODE.NCODETYPEID
     *
     * @param ncodetypeid the value for UTCDBA.XHXT_CODE.NCODETYPEID
     *
     * @mbggenerated
     */
    public void setNcodetypeid(Short ncodetypeid) {
        this.ncodetypeid = ncodetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UTCDBA.XHXT_CODE.CCODEVALUE
     *
     * @return the value of UTCDBA.XHXT_CODE.CCODEVALUE
     *
     * @mbggenerated
     */
    public String getCcodevalue() {
        return ccodevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UTCDBA.XHXT_CODE.CCODEVALUE
     *
     * @param ccodevalue the value for UTCDBA.XHXT_CODE.CCODEVALUE
     *
     * @mbggenerated
     */
    public void setCcodevalue(String ccodevalue) {
        this.ccodevalue = ccodevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UTCDBA.XHXT_CODE.CCODEVALUENOTE
     *
     * @return the value of UTCDBA.XHXT_CODE.CCODEVALUENOTE
     *
     * @mbggenerated
     */
    public String getCcodevaluenote() {
        return ccodevaluenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UTCDBA.XHXT_CODE.CCODEVALUENOTE
     *
     * @param ccodevaluenote the value for UTCDBA.XHXT_CODE.CCODEVALUENOTE
     *
     * @mbggenerated
     */
    public void setCcodevaluenote(String ccodevaluenote) {
        this.ccodevaluenote = ccodevaluenote;
    }
}