package com.rabbit.smart.dao.first.mapper;

import com.rabbit.smart.dao.first.entity.FrmDepartment;
import com.rabbit.smart.dao.first.entity.FrmDepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrmDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_DEPARTMENT
     *
     * @mbggenerated
     */
    int countByExample(FrmDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_DEPARTMENT
     *
     * @mbggenerated
     */
    int deleteByExample(FrmDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_DEPARTMENT
     *
     * @mbggenerated
     */
    int insert(FrmDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_DEPARTMENT
     *
     * @mbggenerated
     */
    int insertSelective(FrmDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_DEPARTMENT
     *
     * @mbggenerated
     */
    List<FrmDepartment> selectByExample(FrmDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_DEPARTMENT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FrmDepartment record, @Param("example") FrmDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.FRM_DEPARTMENT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FrmDepartment record, @Param("example") FrmDepartmentExample example);
}