package com.rabbit.smart.dao.first.mapper;

import com.rabbit.smart.dao.first.entity.SysUser;
import com.rabbit.smart.dao.first.entity.SysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    int countByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    int deleteByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String yhdh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    List<SysUser> selectByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    SysUser selectByPrimaryKey(String yhdh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WWJCPT.SYS_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUser record);
}