package com.rabbit.smart.dao.db1.entity;

import java.util.Date;

public class SysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_ROLE.RID
     *
     * @mbggenerated
     */
    private String rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_ROLE.RNAME
     *
     * @mbggenerated
     */
    private String rname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_ROLE.CJR
     *
     * @mbggenerated
     */
    private String cjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_ROLE.CJSJ
     *
     * @mbggenerated
     */
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_ROLE.IPKS
     *
     * @mbggenerated
     */
    private String ipks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_ROLE.IPJS
     *
     * @mbggenerated
     */
    private String ipjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_ROLE.JSYXQ
     *
     * @mbggenerated
     */
    private Date jsyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WWJCPT.SYS_ROLE.SHQX
     *
     * @mbggenerated
     */
    private String shqx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_ROLE.RID
     *
     * @return the value of WWJCPT.SYS_ROLE.RID
     *
     * @mbggenerated
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_ROLE.RID
     *
     * @param rid the value for WWJCPT.SYS_ROLE.RID
     *
     * @mbggenerated
     */
    public void setRid(String rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_ROLE.RNAME
     *
     * @return the value of WWJCPT.SYS_ROLE.RNAME
     *
     * @mbggenerated
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_ROLE.RNAME
     *
     * @param rname the value for WWJCPT.SYS_ROLE.RNAME
     *
     * @mbggenerated
     */
    public void setRname(String rname) {
        this.rname = rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_ROLE.CJR
     *
     * @return the value of WWJCPT.SYS_ROLE.CJR
     *
     * @mbggenerated
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_ROLE.CJR
     *
     * @param cjr the value for WWJCPT.SYS_ROLE.CJR
     *
     * @mbggenerated
     */
    public void setCjr(String cjr) {
        this.cjr = cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_ROLE.CJSJ
     *
     * @return the value of WWJCPT.SYS_ROLE.CJSJ
     *
     * @mbggenerated
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_ROLE.CJSJ
     *
     * @param cjsj the value for WWJCPT.SYS_ROLE.CJSJ
     *
     * @mbggenerated
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_ROLE.IPKS
     *
     * @return the value of WWJCPT.SYS_ROLE.IPKS
     *
     * @mbggenerated
     */
    public String getIpks() {
        return ipks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_ROLE.IPKS
     *
     * @param ipks the value for WWJCPT.SYS_ROLE.IPKS
     *
     * @mbggenerated
     */
    public void setIpks(String ipks) {
        this.ipks = ipks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_ROLE.IPJS
     *
     * @return the value of WWJCPT.SYS_ROLE.IPJS
     *
     * @mbggenerated
     */
    public String getIpjs() {
        return ipjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_ROLE.IPJS
     *
     * @param ipjs the value for WWJCPT.SYS_ROLE.IPJS
     *
     * @mbggenerated
     */
    public void setIpjs(String ipjs) {
        this.ipjs = ipjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_ROLE.JSYXQ
     *
     * @return the value of WWJCPT.SYS_ROLE.JSYXQ
     *
     * @mbggenerated
     */
    public Date getJsyxq() {
        return jsyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_ROLE.JSYXQ
     *
     * @param jsyxq the value for WWJCPT.SYS_ROLE.JSYXQ
     *
     * @mbggenerated
     */
    public void setJsyxq(Date jsyxq) {
        this.jsyxq = jsyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WWJCPT.SYS_ROLE.SHQX
     *
     * @return the value of WWJCPT.SYS_ROLE.SHQX
     *
     * @mbggenerated
     */
    public String getShqx() {
        return shqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WWJCPT.SYS_ROLE.SHQX
     *
     * @param shqx the value for WWJCPT.SYS_ROLE.SHQX
     *
     * @mbggenerated
     */
    public void setShqx(String shqx) {
        this.shqx = shqx;
    }
}