package com.rabbit.smart.dao.mapper;

import com.rabbit.smart.dao.entity.SysExpense;
import com.rabbit.smart.dao.entity.SysExpenseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbggenerated
     */
    int countByExample(SysExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbggenerated
     */
    int deleteByExample(SysExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbggenerated
     */
    int insert(SysExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbggenerated
     */
    int insertSelective(SysExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbggenerated
     */
    List<SysExpense> selectByExample(SysExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbggenerated
     */
    SysExpense selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysExpense record, @Param("example") SysExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysExpense record, @Param("example") SysExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysExpense record);
}